const data = {
    products : [
        {
            _id:'1',
            name: 'Nike Slim Shirt',
            category: 'Shirts',
            image: '/images/p1.jpg',
            price: 120,
            countInStock: 10,
            brand: 'Nike',
            rating: 4.5,
            numReviews: 10,
            description: 'high quality product',
        },
        {
            _id:'2',
            name: 'Adidas Slim Shirt',
            category: 'Shirts',
            image: '/images/p2.jpg',
            price: 100,
            countInStock: 20,
            brand: 'Adidas',
            rating: 4.0,
            numReviews: 12,
            description: 'high quality product',
        },
        {
            _id:'3',
            name: 'Lascote Free Shirt',
            category: 'Shirts',
            image: '/images/p3.jpg',
            price: 220,
            countInStock: 0,
            brand: 'Lacoste',
            rating: 4.8,
            numReviews: 17,
            description: 'high quality product',
        },
        {
            _id:'4',
            name: 'Nike Slim Pant',
            category: 'Pants',
            image: '/images/p4.jpg',
            price: 78,
            countInStock: 15,
            brand: 'Nike',
            rating: 4.5,
            numReviews: 14,
            description: 'high quality product',
        },
        {
            _id:'5',
            name: 'Puma Slim Pant',
            category: 'Pants',
            image: '/images/p1.jpg',
            price: 78,
            countInStock: 5,
            brand: 'Puma',
            rating: 4.5,
            numReviews: 10,
            description: 'high quality product',
        },
        {
            _id:'6',
            name: 'Addidas Slim Pant',
            category: 'Pants',
            image: '/images/p1.jpg',
            price: 139,
            countInStock: 5,
            brand: 'Addidas',
            rating: 5.0,
            numReviews: 16,
            description: 'high quality product',
        },
    ],
};

export default data;